# HW

In [1]:
import numpy as np

##  #1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?


In [2]:
array1 = np.array([[10, 8], [3, 5]])

In [3]:
# inverse matrix

arr_1_inv = np.linalg.inv(array1)
arr_1_inv

array([[ 0.19230769, -0.30769231],
       [-0.11538462,  0.38461538]])

In [5]:
answer = arr_1_inv @ array1

if answer.all() == np.identity(2).all():
    print("Yes, the result is the same as identity")
else:
    print("Nope") #question1

Yes, the result is the same as identity


## #2. 運用上列array計算特徵值、特徵向量


In [6]:
w, v = np.linalg.eig(array1)

print("eigenvalues = {}\neigenvectors = \n{}".format(w, v))

eigenvalues = [13.  2.]
eigenvectors = 
[[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


## #3. 運用上列array計算SVD?


In [7]:
u, s, vh = np.linalg.svd(array1)

In [8]:
print("SVD: \n u = \n{}\ns = {}\n vh = \n{}".format(u, s, vh))

SVD: 
 u = 
[[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]]
s = [13.94721714  1.86417116]
 vh = 
[[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]
