In [1]:
import numpy as np

# HW

## #.1 將下兩列array存成npz檔

* array1 = np.array(range(30))
* array2 = np.array([2,3,5])

In [3]:
array1 = np.arange(30)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
array2 = np.array([2, 3, 5])
array2

array([2, 3, 5])

In [6]:
with open("double_array.npz", "wb") as f:
    np.savez(f, array1, array2)

In [8]:
#check

check = np.load("double_array.npz")
check.files

['arr_0', 'arr_1']

In [9]:
check["arr_0"]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [10]:
check["arr_1"]

array([2, 3, 5])

## #2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔

* array3 = np.array([[4,5,6], [1,2,3]])

In [11]:
array3 = np.array([[4,5,6], [1,2,3]])

In [12]:
np.savez("answer.npz", check['arr_0'], check['arr_1'], array3)

In [13]:
#check
check = np.load("answer.npz")

In [14]:
check.files

['arr_0', 'arr_1', 'arr_2']

In [15]:
check['arr_0']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [16]:
check['arr_1']

array([2, 3, 5])

In [17]:
check['arr_2']

array([[4, 5, 6],
       [1, 2, 3]])