In [1]:
import numpy as np

In [3]:
array1 = np.arange(30)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

# HW
## #1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")


In [5]:
array1 = array1.reshape((5, 6), order = "F")

In [6]:
array1

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

## #2.呈上題的array，找出被6除餘1的數的索引


In [7]:
np.where((array1 % 6) == 1)

(array([0, 1, 2, 3, 4]), array([5, 0, 1, 2, 3]))

In [9]:
print(array1[0, 5])
print(array1[1, 0])
print(array1[2, 1])
print(array1[3, 2])
print(array1[4, 3])

25
1
7
13
19
